# Generated by Django 4.1.2 on 2022-10-11 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('gender', models.CharField(choices=[('DEFAULT', '-----'), ('M', 'Male'), ('F', 'Female')], default='DEFAULT', max_length=50)),
                ('country', models.CharField(choices=[('DEFAULT', '-----'), ('FRC', 'France'), ('JPA', 'Japan'), ('NGA', 'Nigeria'), ('USA', 'USA')], default='DEFAULT', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
