# Generated by Django 4.1.2 on 2022-10-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(choices=[('FRC', 'France'), ('JPA', 'Japan'), ('NGA', 'Nigeria'), ('USA', 'USA')], default='-----', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='-----', max_length=50),
        ),
    ]
