# Generated by Django 4.1.2 on 2022-10-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_author_country_alter_author_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(choices=[('DEFAULT', '-----'), ('FRC', 'France'), ('JPA', 'Japan'), ('NGA', 'Nigeria'), ('USA', 'USA')], default='DEFAULT', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('DEFAULT', '-----'), ('M', 'Male'), ('F', 'Female')], default='DEFAULT', max_length=50),
        ),
    ]
